### PR TITLE
Manual Python 3.9 Migration 

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
Why is this needed, isn't this package `noarch: python`?

**Comment by jan-janssen** [comment]
Currently I can not install it in a Python 3.9 environment, I get the following error: 
```
six[version='>=1.14.0'] -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']
```
In addition there was a python 3.8 migration before.

**Comment by chrisburr** [comment]
`mamba create --name test python=3.9 six` works so I think it's just conda's conflict message being unclear (it's probably found a corner of the space where it uses an older build of `six`).

Can you share the conda command that fails? (Or the PR if it's a conda-build that's failing)

**Comment by jan-janssen** [comment]
I try to update our test environment: 
https://github.com/pyiron/pyiron/pull/1130

**Comment by chrisburr** [comment]
I've not looked why it hasn't been migrated but this should help get you there, else we can continue on gitter:
```python
$ mamba env create --file environment.yml --name pyiron
conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change


Looking for: ['python=3.9', "ase[version='>=3.20']", 'coveralls', 'coverage', 'codacy-coverage', "defusedxml[version='>=0.6.0']", "dill[version='>=0.3.1.1']", "future[version='>=0.18.2']", "h5py[version='>=2.10.0']", "matplotlib[version='>=3.2.0']", "mendeleev[version='>=0.5.2']", "molmod[version='>=1.4.5']", "numpy[version='>=1.18.1']", "pandas[version='>=1.0.1']", "phonopy[version='>=2.4.2']", "pymatgen[version='>=2020.9.14']", "pyiron_base[version='>=0.1.24']", "pyscal[version='>=2.7.5']", "pytables[version='>=3.6.1']", "quickff[version='>=2.2.4']", "scipy[version='>=1.4.1']", "seekpath[version='>=1.9.4']", "six[version='>=1.14.0']", "scikit-learn[version='>=0.22']", "spglib[version='>=1.14.1']", "tamkin[version='>=1.2.6']", "tqdm[version='>=4.43.0']", "yaff[version='>=1.4.2']"]


Encountered problems while solving.
Problem: package yaff-1.4.2-py27h516909a_2 requires python >=2.7,<2.8.0a0, but none of the providers can be installed
```

**Pull request closed without merging**
